import "../globals.css";

import Dashboard from "@/components/dashboard/Home";
import Nav from "@/components/layout/Nav";
import { Toaster } from "@/components/ui/toaster";

export const metadata = {
  title: "Anol",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Nav />
      <Dashboard>{children}</Dashboard>
      <Toaster />
    </>
  );
}
 