# Generated by Django 4.2 on 2024-02-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_purchaseitem_purchaseorder_salesitem_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="cost_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
        migrations.AddField(
            model_name="product",
            name="stock_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
