# Generated by Django 4.2 on 2024-10-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_salesitem_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="unit_price",
            field=models.BigIntegerField(help_text="Cost price"),
        ),
    ]
