# Generated by Django 4.2 on 2024-10-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_product_cost_price_alter_purchaseitem_unit_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="selling_price",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="cost_price",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="salesitem",
            name="unit_price",
            field=models.BigIntegerField(verbose_name="Sold at"),
        ),
    ]
