# Generated by Django 4.2 on 2024-02-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_purchaserecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock_quantity",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Total Amount Spent"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
