# Generated by Django 4.2 on 2024-02-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_purchaseorder_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_number",
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
