# Generated by Django 4.2 on 2024-02-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_purchaseorder_order_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaserecord",
            name="product",
        ),
        migrations.AddField(
            model_name="purchaserecord",
            name="product",
            field=models.ManyToManyField(to="base.product"),
        ),
    ]
