# Generated by Django 4.2 on 2024-02-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_remove_purchaserecord_product_purchaserecord_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salesitem",
            name="sales_transaction",
        ),
        migrations.AlterField(
            model_name="salesitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Sold at"
            ),
        ),
        migrations.DeleteModel(
            name="SalesTransaction",
        ),
    ]
