# Generated by Django 4.2 on 2024-02-14 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_remove_salesitem_sales_transaction_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaserecord",
            name="purchase_order",
        ),
        migrations.RemoveField(
            model_name="purchaserecord",
            name="purchase_price",
        ),
        migrations.AddField(
            model_name="purchaserecord",
            name="supplier",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.supplier",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchaserecord",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=52000,
                max_digits=10,
                verbose_name="Total Amount Spent",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.purchaserecord"
            ),
        ),
        migrations.RemoveField(
            model_name="purchaserecord",
            name="product",
            field=models.ManyToManyField(
                to="base.product"
            ),
        ),
        migrations.AddField(
            model_name="purchaserecord",
            name="product",
            field=models.ManyToManyField(
                through="base.PurchaseItem", to="base.product"
            ),
        ),
        migrations.DeleteModel(
            name="PurchaseOrder",
        ),
    ]
