import { Fragment } from "react";
import "../globals.css";

export const metadata = {
  title: "Anol",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <Fragment>{children}</Fragment>;
}
