# Generated by Django 4.2.3 on 2024-02-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "email",
                    models.EmailField(
                        max_length=80, unique=True, verbose_name="Email address"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="Username"
                    ),
                ),
                ("date_joined", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_login", models.DateTimeField(auto_now=True, null=True)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "User",
                "ordering": ["email"],
            },
        ),
    ]
