# Generated by Django 4.2 on 2024-10-27 16:52


from django.db import migrations


def remove_conditional_unique_constraint(apps, schema_editor):
    # Use schema_editor to remove the conditional unique constraint if it exists
    # You may need to adapt this according to your specific model and field
    schema_editor.execute("ALTER TABLE users DROP INDEX 1")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_account_is_superuser"),
    ]

    operations = [
        migrations.RunPython(remove_conditional_unique_constraint),
    ]
